---
title: "AYA LGG DFCI BulkRNASeq"
output: html_document
date: "2022-08-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

########## Initialize ##########
Install global packages and functions
```{r}
library(tidyverse)
library(readxl)
library(pheatmap)
library(ggplot2)
library(reshape2)
library(dplyr)
library(DESeq2)

source("~/Dropbox (Partners HealthCare)/Filbin/Jacob/dfci-pnoc/bulkRNAseq-scripts.R")

wd <- c("~/Dropbox (Partners HealthCare)/Filbin/Jacob/Projects/AYA Bulk RNA-seq/")
fwd <- c(paste0(wd, "Figures/"))
```

########## Load Data ##########
Load bulk RNAseq Data
```{r}
txi.rsem <- MakeCountMatrixWithTximport(filePath = "~/Dropbox (Partners HealthCare)/Filbin/Jacob/Projects/AYA Bulk RNA-seq/star-rsem/", method = "rsem")
patient_ids <- txi.rsem$counts %>% colnames() %>% unique()
```

Load AYA clinical data
``` {r}
meta <- read_excel("~/Dropbox (Partners HealthCare)/Filbin/Jacob/Projects/AYA Bulk RNA-seq/Deidentified RNAseq Patient Clinical Data.xlsx", skip = 1)
meta <- meta %>%
  mutate(SampleID = paste0("s", sapply(strsplit(as.character(meta$SampleID), "-"), `[`, 1))) %>% 
  # only keeps sample ID before "-"
  dplyr::distinct(SampleID, .keep_all = TRUE) %>%
  filter(SampleID %in% patient_ids) %>%
  filter(SampleID != "94410-1*") %>%
  mutate(time = as.numeric(`Overall Survival (Years)`)) %>% 
  mutate(diagnosis_old = as.factor(`Pathology at Diagnosis`)) %>%
  mutate(diagnosis = ifelse(`Pathology at Diagnosis` %in% c("Anaplastic Astrocytoma, WHO Grade III, IDH-Mutant", "Diffuse Astrocytoma, WHO Grade II, IDH-Mutant"), "Astrocytoma",
                            ifelse(`Pathology at Diagnosis` == "Oligodendroglioma, WHO Grade II", "Oligodendroglioma", "Glioblastoma"))) %>%
  mutate(diagnosis = as.factor(diagnosis)) %>%
  mutate(status = ifelse(`Vital Status` == "Alive", 1, 2)) # this will be used in `status` in survival package

# check
meta$SampleID %in% patient_ids %>% table()
patient_ids %in% meta$SampleID %>% table()
```

```{r}
dds <- DESeqDataSetFromTximport(txi = txi.rsem, colData = meta, design = ~1)
```


Survival on clinical data
```{r}
library(survival)
library(survminer)

fit <- survfit(Surv(time = time, status) ~ diagnosis_old, data = meta)
pvalue <- surv_pvalue(fit, meta)$pval.txt
survivalPlot <- ggsurvplot(fit,
           risk.table = TRUE, 
           risk.table.y.text = FALSE,
           risk.table.height = 0.25)
# remove GBM sample
# rerun survival analysis by comining both astrocytoma diagnosis types

patient_ids.new <- meta %>% filter(diagnosis %in% c("Astrocytoma", "Oligodendroglioma")) %>% pull(SampleID)

fit.new <- survfit(Surv(time = time, status) ~ diagnosis, data = meta)
pvalue <- surv_pvalue(fit.new, meta)$pval.txt
survivalPlot.new <- ggsurvplot(fit.new,
           risk.table = TRUE, 
           risk.table.y.text = FALSE,
           risk.table.height = 0.25)
```


Update dds object 
```{r}
dds <- dds[, colnames(dds) %in% patient_ids.new]
# removed GBM sample
```

########## Create gene signature on Astro/Oligo differences ##########
Install packages
```{r}
library(clusterProfiler)
library(enrichplot)
library(org.Hs.eg.db)
library(EnhancedVolcano)
```

```{r}
design(dds) <- formula(~diagnosis)
dds <- DESeq(dds)
res <- na.omit(results(dds, contrast=c("diagnosis", "Astrocytoma", "Oligodendroglioma")))
res <- as.data.frame(res)
res <- res[order(res$padj),]
res$Group <- ifelse(res$log2FoldChange > 0, "Astro", "Oligo")

a <- EnhancedVolcano(res,
                lab=rownames(res),
                x="log2FoldChange",
                y="padj",
                title="Astro v Oligo Signature Expression",
                subtitle = "",
                pCutoff=0.05,
                FCcutoff = .75,
                col=c('black', 'black', 'black', 'red3'),
                ylab = "-Log10(p.adj)")

astro.genes <- filter(res, padj < 0.05 & log2FoldChange > 0) %>% arrange(-log2FoldChange) %>% rownames() %>% unique()
oligo.genes <- filter(res, padj < 0.05 & log2FoldChange < 0) %>% arrange(log2FoldChange) %>% rownames() %>% unique()

astro.up <- enrichGO(gene = astro.genes,
         universe = as.character(rownames(res)),
         OrgDb = org.Hs.eg.db,
         keyType = 'ENSEMBL',
         ont = "BP",
         pAdjustMethod = "BH",
         qvalueCutoff = 0.05,
         readable = FALSE) %>%
  enrichplot::pairwise_termsim() %>%
  dotplot(showCategory = 30)

oligo.up <- enrichGO(gene = oligo.genes,
         universe = as.character(rownames(res)),
         OrgDb = org.Hs.eg.db,
         keyType = 'ENSEMBL',
         ont = "BP",
         pAdjustMethod = "BH",
         qvalueCutoff = 0.05,
         readable = FALSE) %>%
  enrichplot::pairwise_termsim() %>%
  dotplot(showCategory = 30)

saveRDS(dds, file = paste0(wd, "DFCIAYAData.Rds"))
```

Add gene signatures to meta data
```{r}
meta <- ScoreSignatureAndSplit(countMatrix.center = input$countMatrix_center,
                                countMatrix.mean = input$countMatrix_mean,
                                metaData = meta,
                                s = syn_genesets$curatedSynaptic$gluta,
                                geneSetName = "gluta",
                                splitBy = "Median",
                                verbose = TRUE)
meta <- ScoreSignatureAndSplit(countMatrix.center = input$countMatrix_center,
                               countMatrix.mean = input$countMatrix_mean,
                               metaData = meta,
                               s = syn_genesets$curatedSynaptic$gaba,
                               geneSetName = "gaba",
                               splitBy = "Median",
                               verbose = TRUE)
test <- ScoreSurvival(metaData = meta, geneSetName = "gaba")
test$plot
```

